

LIBPATH = ['/usr/local/Cellar/tclap/1.2.1/include','/usr/local/Cellar/boost/1.55.0_1/include']

context = ['context.cpp']
Program('composecon',['composecon.cpp']+context)
Program('mergecon',['mergecon.cpp']+context)
Program('csv2con',['csv2con.cpp']+context)
Program('restrictcon',['restrictcon.cpp']+context)
Program('reverscon',['reversecon.cpp']+context)
Program('tab2con',['table2context.cpp']+context)
Program('kludgecon',['kludgecon.cpp']+context)
Program('cat2con',['category2con.cpp']+context)

concept = ['concept.cpp']

chain = ['chain.cpp']
chainmap = ['chain_map.cpp']



lattice = ['lattice.cpp']

Program('countattr',['countattributes.cpp']+concept+lattice)
Program('countobj',['countobjects.cpp']+concept+lattice)
Program('depattr',['depchain.cpp','depchaintable.cpp']+concept+chain+chainmap+lattice)


Program('buildfreqtab',['buildfreqtable.cpp']+concept+lattice)
